export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Home } from './Home'
export { default as AllPosts } from './AllPosts'
export { default as Post } from './Post'
export { default as AddPost } from './AddPost'
export { default as EditPost } from './EditPost'
export { default as Profile } from './Profile'